# Site
theme: jekyll-theme-chirpy
lang: en
timezone: Europe/London
url: "https://www.jupiterzw.com"
baseurl:

# Identity and metadata
title: Zhiyu Wang
tagline: Welcome to the club, pal.
description: >-
  My name is Zhiyu Wang (Peter). I am currently a master student in  mathematics
  at University of Oxofrd. Prior to that, I received BSc in Mathematics from
  University College London. My academic interests lie in Statistical and
  Computational Learning Theory, Theories of Deep Learning, as well as
  Theoretical Neuroscience, fields which I believe provide important insights
  into understanding intelligence. I am also interested in Rough Path Theory
  and Stochastic Analysis.

github:
  username: jupiterzw

social:
  name: Zhiyu Wang
  email: peter.wang.21@ucl.ac.uk
  links:
    - https://github.com/jupiterzw

# Appearance and site features
avatar: "/assets/img/avatar.jpg"
toc: true
paginate: 10

pwa:
  enabled: true

comments:
  active: giscus
  giscus:
    repo: "jupiterzw/jupiterzw.github.io"
    repo_id: "R_kgDOJ-FPaA"
    category: "Announcements"
    category_id: "DIC_kwDOJ-FPaM4CbYLc"

# Content collections and URLs
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Markdown, Sass, and HTML output
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  load_paths:
    - node_modules
    - _vendor/chirpy-legacy-sass
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Files used for development but not copied into the generated site
exclude:
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package*.json
  - scripts
  - vendor
