# frozen_string_literal: true

# Replaces known cover and avatar <img> tags with responsive AVIF/WebP
# <picture> elements. The image variants and manifest are generated by
# scripts/build-responsive-images.mjs before Jekyll starts.

require "cgi"

module ResponsiveImages
  IMG_TAG = /<img\b[^>]*>/i
  SRC_ATTRIBUTE = /\bsrc=(["'])(.*?)\1/i

  module_function

  def remove_attribute(tag, name)
    tag.gsub(/\s#{Regexp.escape(name)}=(["']).*?\1/i, "")
  end

  def set_attribute(tag, name, value)
    escaped_value = CGI.escapeHTML(value.to_s)
    attribute = %(#{name}="#{escaped_value}")

    if tag.match?(/\s#{Regexp.escape(name)}=(["']).*?\1/i)
      tag.sub(/\s#{Regexp.escape(name)}=(["']).*?\1/i, " #{attribute}")
    else
      tag.sub(/\s*\/?>\z/, " #{attribute}>")
    end
  end

  def set_attribute_unless_present(tag, name, value)
    return tag if tag.match?(/\s#{Regexp.escape(name)}=(["']).*?\1/i)

    set_attribute(tag, name, value)
  end

  def variant_url(source, baseurl)
    "#{baseurl}#{source}"
  end

  def srcset(variants, baseurl)
    variants.map do |variant|
      "#{variant_url(variant.fetch("src"), baseurl)} #{variant.fetch("width")}w"
    end.join(", ")
  end

  def sizes_for(layout, role)
    return "112px" if role == "avatar"

    if layout == "home"
      "(min-width: 1200px) 420px, (min-width: 768px) 38vw, calc(100vw - 24px)"
    else
      "(min-width: 1200px) 860px, (min-width: 768px) calc(100vw - 260px), calc(100vw - 32px)"
    end
  end

  def optimize(output, document, manifest)
    layout = document.data["layout"].to_s
    baseurl = document.site.config["baseurl"].to_s.sub(%r{/$}, "")
    cover_index = 0

    output.gsub(IMG_TAG) do |tag|
      source_match = tag.match(SRC_ATTRIBUTE)
      next tag unless source_match

      source = source_match[2].split(/[?#]/, 2).first
      lookup_source = baseurl.empty? ? source : source.sub(/\A#{Regexp.escape(baseurl)}/, "")
      image = manifest[lookup_source]
      next tag unless image

      role = image.fetch("role")
      critical_cover =
        role == "cover" &&
        (layout == "post" || (layout == "home" && cover_index.zero?))

      cover_index += 1 if role == "cover"

      optimized_tag = set_attribute(tag, "decoding", "async")

      if layout == "home" && role == "cover"
        optimized_tag = set_attribute_unless_present(optimized_tag, "width", 800)
        optimized_tag = set_attribute_unless_present(optimized_tag, "height", 420)
      else
        optimized_tag = set_attribute_unless_present(
          optimized_tag,
          "width",
          image.fetch("width"),
        )
        optimized_tag = set_attribute_unless_present(
          optimized_tag,
          "height",
          image.fetch("height"),
        )
      end

      if critical_cover
        optimized_tag = set_attribute(optimized_tag, "loading", "eager")
        optimized_tag = set_attribute(optimized_tag, "fetchpriority", "high")
      elsif role == "cover"
        optimized_tag = set_attribute(optimized_tag, "loading", "lazy")
        optimized_tag = set_attribute(optimized_tag, "fetchpriority", "low")
      else
        optimized_tag = remove_attribute(optimized_tag, "loading")
        optimized_tag = set_attribute(optimized_tag, "fetchpriority", "low")
      end

      sizes = sizes_for(layout, role)
      avif = srcset(image.fetch("avif"), baseurl)
      webp = srcset(image.fetch("webp"), baseurl)

      [
        '<picture class="responsive-image">',
        %(<source type="image/avif" srcset="#{avif}" sizes="#{sizes}">),
        %(<source type="image/webp" srcset="#{webp}" sizes="#{sizes}">),
        optimized_tag,
        "</picture>",
      ].join
    end
  end
end

Jekyll::Hooks.register %i[pages documents], :post_render do |document|
  next unless document.output_ext == ".html"

  manifest = document.site.data["responsive_images"]
  next if manifest.nil? || manifest.empty?

  document.output = ResponsiveImages.optimize(document.output, document, manifest)
end
